# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-24 07:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('send_date', models.DateTimeField()),
                ('text', models.TextField()),
                ('users_read', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
